version: 2.1
parameters:
  test_run_ids:
    type: string
    default: ""
  testing_environment:
    type: string
    default: "dev"
  run_all_tests:
    type: boolean
    default: true

executors:
  playwright:
    docker:
      - image: "cimg/node:18.10"
      - image: "mcr.microsoft.com/playwright:v1.40.1"
      - image: "cimg/go:1.18.1"
    working_directory: ~/project
commands:
  checkout_and_install_node:
    resource_class: wrzmwufrzwq5epqqvpmy39/learn_playwright
    description: checkout and install dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}'
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: 'node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}'
          paths:
            - ./node_modules
  install_playwright_browsers:
    description: install browsers of playwright
    steps:
      - run:
          name: Install Playwright Browsers
          command: "npm run install:browsers"
  
jobs:
  run_e2e_testing:
    machine: true
    resource_class: wrzmwufrzwq5epqqvpmy39/learn_playwright
    steps: 
     - run:
        echo 'Hi I am Runner'
        echo ${CIRCLE_NODE_INDEX}
        echo ${SHARD}
        echo ${CIRCLE_NODE_TOTAL}

workflows:
  testing:
    jobs:
      - run_e2e_testing

  