version: 2.1
  
jobs:
  run_e2e_testing:
    machine: true
    resource_class: wrzmwufrzwq5epqqvpmy39/learn_playwright
    steps: 
     - run:
        echo 'Hi I am Runner'
        echo ${CIRCLE_NODE_INDEX}
        echo ${SHARD}
        echo ${CIRCLE_NODE_TOTAL}

workflows:
  testing:
    jobs:
      - run_e2e_testing

  