version: 2.1
parameters:
  test_run_ids:
    type: string
    default: ""
  testing_environment:
    type: string
    default: "dev"
  run_all_tests:
    type: boolean
    default: true
executors:
  playwright:
    docker:
      - image: "cimg/node:18.10"
      - image: "mcr.microsoft.com/playwright:v1.40.1"
      - image: "cimg/go:1.18.1"
    working_directory: ~/project
commands:
  checkout_and_install_node:
    description: checkout and install dependencies
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
  install_playwright_browsers:
    description: install browsers of playwright
    steps:
      - run:
          name: Install Playwright Browsers
          command: "npm run install:browsers"
  store_test_results_and_artifacts:
    steps:
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: playwright-report
jobs:
  run_e2e_testing:
    executor:
      name: playwright
    parallelism: 1
    resource_class: wrzmwufrzwq5epqqvpmy39/learn_playwright
    parameters:
      script:
        type: string
        default: "test:chromium"
    steps:
      - run: echo "Hi I'm on a Container Runner!"
      - checkout_and_install_node
      - install_playwright_browsers
      - run:
          name: Execute End-to-End Testing
          command: "npm run test-staging --TAGS='@login'"
      - store_test_results_and_artifacts

workflows:
  run_automation_testing_simple_workflow:
    jobs:
      - run_e2e_testing
